#cloud-config
package_update: true
packages:
  - apache2

write_files:
  - path: /var/www/html/index.html
    owner: root:root
    permissions: "0644"
    defer: true
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>Week 7 assignment</title>
      </head>
      <body>
        <h1>Hello from ${student_name}!</h1>
        <p>${page_message}</p>
      </body>
      </html>

runcmd:
  - systemctl enable -- now apache2
